BATCH: false
SPLIT:
  GRID: 0
  EDGE_WIDTH: 50
  DILATE_ROUND: 3
TRACKER:
  DISPLACE: 40
  GAP_FILL: 5
POST_PROCESS:
  MIN_G: 6
  MIN_S: 5
  MIN_M: 3
  REFINER:
    MODE: SVM
    SMOOTH: 5
    # TRH mode only
    MAX_DIST_TRH: 100
    MAX_FRAME_TRH: 5
    # SVM mode only
    SEARCH_RANGE: 5
    MITOSIS_LEN: 5
    SAMPLE_FREQ: 0.05
    SVM_MODEL_PATH: '../models/mitosis_svm.m'
  RESOLVER:
    MIN_TRACK: 10
