BATCH: false
PIX_SATURATE: 1
GAMMA: 1
SPLIT:
  GRID: 0
  EDGE_WIDTH: 20
  DILATE_ROUND: 3
EDGE_FLT: 10
SIZE_FLT: 800
TRACKER:
  DISPLACE: 80
  GAP_FILL: 10
POST_PROCESS:
  MAX_BG: 5
  MIN_S: 20
  MIN_M: 10
  REFINER:
    MASK_CONSTRAINT:
      ENABLED: true
      DILATE_FACTOR: 0.5
    SMOOTH: 5
    MITOSIS_LEN: 25
    SAMPLE_FREQ: 0.2
    SEARCH_RANGE: 10
    MODE: TRH
    # TRH mode only
    MAX_DIST_TRH: 80
    MAX_FRAME_TRH: 30
    # SVM mode only
    ASO_TRH: 0.8
    SVM_TRAIN_DATA: '../models/SVM_train.txt'
  RESOLVER:
    MIN_LINEAGE: 10
    G2_TRH: 100
