BATCH: false
PIX_SATURATE: 1.2
GAMMA: 1
SPLIT:
  GRID: 0
  EDGE_WIDTH: 20
  DILATE_ROUND: 3
EDGE_FLT: 10
SIZE_FLT: 800
TRACKER:
  DISPLACE: 60
  GAP_FILL: 10
POST_PROCESS:
  MIN_BG: 5
  MIN_S: 20
  MIN_M: 10
  REFINER:
    MASK_CONSTRAINT:
      ENABLED: false
      DILATE_FACTOR: 0.5
    SMOOTH: 5
    MITOSIS_LEN: 25
    SAMPLE_FREQ: 0.2
    SEARCH_RANGE: 10
    MODE: TRH
    # TRH mode only
    MAX_DIST_TRH: 100
    MAX_FRAME_TRH: 25
    # SVM mode only
    ASO_TRH: 0.5
    SVM_TRAIN_DATA: '../models/SVM_train.txt'
  RESOLVER:
    MIN_TRACK: 50
    G2_TRH: 100
