BATCH: false
SPLIT:
  GRID: 0
  EDGE_WIDTH: 50
  DILATE_ROUND: 3
TRACKER:
  DISPLACE: 60
  GAP_FILL: 5
POST_PROCESS:
  MIN_G: 25
  MIN_S: 20
  MIN_M: 10
  REFINER:
    SMOOTH: 5
    MITOSIS_LEN: 25
    SAMPLE_FREQ: 0.2
    MODE: TRH
    # TRH mode only
    MAX_DIST_TRH: 100
    MAX_FRAME_TRH: 25
    # SVM mode only
    SEARCH_RANGE: 20
    SVM_TRAIN_DATA: '../models/SVM_train.txt'
  RESOLVER:
    MIN_TRACK: 50
    G2_TRH: 100
